DROP TABLE IF EXISTS ATHLETE;

CREATE TABLE ATHLETE (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  PRIMARY_SPORT VARCHAR(250) DEFAULT NULL,
  SECONDARY_SPORT VARCHAR(250) DEFAULT NULL
);

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, PRIMARY_SPORT, SECONDARY_SPORT) VALUES
  ('Faisal', 'Khan', 'RUNNING', 'CYCLING'),
  ('Ellen', 'Abarr', 'SWIMMING', null),
  ('John', 'Smith', 'SWIMMING', 'RUNNING'),
  ('Bob', 'Jonson', 'CYCLING',null);